# Generated by Django 4.2.6 on 2024-01-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='айди чата'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Telegram'),
        ),
    ]
