# Generated by Django 4.2.6 on 2023-10-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='time_for',
            new_name='time_required',
        ),
    ]
