# Generated by Django 4.2.6 on 2023-10-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(verbose_name='время, когда необходимо выполнять'),
        ),
    ]
